# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.35.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "FastlaneExampleTests")
  end

  desc "Runs all the UI tests"
  lane :ui_test do
    scan(scheme: "FastlaneExampleUITests")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # Sign with AppStore certificate
    match(type: "appstore")
    # set build number to current timestamp (avoid conflicts in iTunes)
    increment_build_number(build_number: Time.now.getutc.to_i)
    # Builds FastlaneExample
    gym(scheme: "FastlaneExample")
    # Ships to Testflight
    pilot(skip_waiting_for_build_processing: true)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # Sign with Appstore certificate
    match(type: "appstore")
    # set build number to current timestamp (avoid conflicts in iTunes)
    increment_build_number(build_number: Time.now.getutc.to_i)
    # Builds FastlaneExample
    gym(scheme: "FastlaneExample")
    # Ships to iTunes Connect
    deliver(force: true)
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
